# -*- coding: utf-8 -*-
"""Stable Diffusion Easylized - Coded by Ujhhgtg

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HuyJTnfaSnzqLEwe8Pvs3KyKHw--ULin
"""

#@title ### 1. --- User Configuration Section --- {display-mode: "form"}

#@markdown # Select The Desired Models
#@markdown # (find more models at rentry.org/sdmodels)
official = False  #@param {'type': 'boolean'}
nai = True  #@param {'type': 'boolean'}
waifu = False  #@param {'type': 'boolean'}
trinart = False  #@param {'type': 'boolean'}

#@markdown # IMPORTANT NOTICE:
#@markdown # if the code suddenly stops running and shows ^C
#@markdown # while it is loading weights, tick the following
oHNo_My_SErVEr_cRaShEs_HeLP_mE = False #@param {'type': 'boolean'}

#@title ### 2. Download and Install

%cd /content/

## download accelerator & update system
#!apt update -y
#!apt dist-upgrade -y
!apt install -y aria2
# %clear

## webui
!echo "Downloading or updating webui......"
!git clone https://github.com/AUTOMATIC1111/stable-diffusion-webui /content/stable-diffusion-webui/
%cd /content/stable-diffusion-webui/
!git pull
!echo "Done."\n

## extensions for webui
!echo "Downloading or updating plugins......"
!git clone https://github.com/AUTOMATIC1111/stable-diffusion-webui-aesthetic-gradients /content/stable-diffusion-webui/extensions/aesthetic-gradients/
%cd /content/stable-diffusion-webui/extensions/aesthetic-gradients/
!git pull
!git clone https://github.com/yfszzx/stable-diffusion-webui-images-browser /content/stable-diffusion-webui/extensions/images-browser/
%cd /content/stable-diffusion-webui/extensions/images-browser/
!git pull
!git clone https://github.com/deforum-art/deforum-for-automatic1111-webui/ /content/stable-diffusion-webui/extensions/deforum/
%cd /content/stable-diffusion-webui/extensions/deforum/
!git pull
%clear

## xformers - accelerate picture generation
#if xformers == True:
#  %cd /content/
#  !git clone https://github.com/facebookresearch/xformers.git /content/xformers/
#  %cd /content/xformers/
#  !git submodule update --init --recursive
#  %pip install -r requirements.txt
#  %pip install -e .

## models
!mkdir -p /content/stable-diffusion-webui/models/Stable-diffusion /content/stable-diffusion-webui/models/hypernetworks
%cd /content/stable-diffusion-webui/models/Stable-diffusion/

# Official Stable Diffusion
if official == True:
  !echo "Downloading official diffusion model......"
  !curl -Lo official.ckpt https://drive.yerf.org/wl/?id=EBfTrmcCCUAGaQBXVIj5lJmEhjoP1tgl&mode=grid&download=1
  !echo "Done."\n

# Novel AI
if nai == True:
  !echo "Downloading Novel AI model......"
  !aria2c --summary-interval=3 -x 3 -c -Z \
    https://huggingface.co/acheong08/secretAI/resolve/main/stableckpt/animefull-final-pruned/model.ckpt \
    https://huggingface.co/acheong08/secretAI/resolve/main/stableckpt/animefull-final-pruned/config.yaml
  !curl -Lo nai.vae.pt https://cloudflare-ipfs.com/ipfs/bafybeiccldswdd3wvg57jhclcq53lvsc6gizasiblwayvhlv6eq4wow7wu/animevae.pt
  !curl -L https://cloudflare-ipfs.com/ipfs/bafybeiduanx2b3mcvxlwr66igcwnpfmk3nc3qgxlpwh6oq6m6pxii3f77e/_modules.tar | tar x -C /content/stable-diffusion-webui/models/hypernetworks
  !mv config.yaml nai.yaml
  !mv model.ckpt nai.ckpt
  !echo "Done."\n

# Waifu Diffusion
if waifu == True:
  !echo "Downloading Waifu Diffusion......"
  !aria2c --summary-interval=3 -x 3 -c -Z \
    https://huggingface.co/hakurei/waifu-diffusion-v1-3/resolve/main/wd-v1-3-float32.ckpt
  !echo "Done."\n

# Trinart
if trinart == True:
  !echo "Downloading Trinart model......"
  !curl -Lo trinart.ckpt https://huggingface.co/naclbit/trinart_stable_diffusion_v2/resolve/main/trinart2_step115000.ckpt
  !echo "Done."\n

## web ui tunneling tool
!echo "Downloading web ui tunneling tool......"
!curl -Ls https://github.com/ekzhang/bore/releases/download/v0.4.0/bore-v0.4.0-x86_64-unknown-linux-musl.tar.gz | tar zx -C /usr/bin
!curl -Lo /usr/bin/cloudflared https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 && chmod +x /usr/bin/cloudflared
!echo "Done."\n

%clear

#@title ### 3. Clear RAM (will crash Colab, everything will be intact don't worry)

import os
os.kill(os.getpid(), 9)

#@title ### 4. Set Up and Start Server

%cd /content/stable-diffusion-webui/
if oHNo_My_SErVEr_cRaShEs_HeLP_mE == False:
  !COMMANDLINE_ARGS="--medvram" REQS_FILE=requirements.txt python launch.py & bore local 7860 --to bore.pub & cloudflared tunnel --url localhost:7860
else:
  !COMMANDLINE_ARGS="--lowvram" REQS_FILE=requirements.txt python launch.py & bore local 7860 --to bore.pub & cloudflared tunnel --url localhost:7860
